services:
  service_1_postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: container_service_1_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}, -d $${POSTGRES_DB}"]

volumes:
  pgdata:

#sql view all rows from a database table: SELECT * FROM table_name;